

services:
  prometheus:
   image: prom/prometheus
   container_name: prometheus
   networks:
     - monitoring
   ports:
     - "9091:9090"
   volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
   image: grafana/grafana
   container_name: grafana
   networks:
     - monitoring
   ports:
     - "9090:3000"

  node_app:
    build: .
    container_name: node_app
    ports:
      - 3000:3000
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge 